name: Build-Push to Docker Hub & GHCR
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Image tag
        required: true
        default: latest
env:
  IMAGE: culturecloud/mltb
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: pseudokawaii
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build & Push
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            culturecloud/tachidesk:${{ inputs.tag }}
            ghcr.io/culturecloud/tachidesk:${{ inputs.tag }}
